---
kind: pipeline
name: rust-stable

volumes:
- name: cargo-cache
  host:
    path: /var/lib/cargo-cache

steps:
- name: build
  image: rust:1.46
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build

- name: test
  image: rust:1.46
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test
    - git rev-parse HEAD > .tags

- name: release
  image: rust:1.46
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build --release

- name: prep-upload
  image: rust:1.46
  commands:
    - mkdir -p artifacts/$(cat .tags)
    - cp target/meta-matrix artifacts/$(cat .tags)

- name: upload-artifacts
  image: plugins/s3
  settings:
    bucket: meta-matrix
    access_key:
      from_secret: s3_access_key
    secret_key:
      from_secret: s3_secret_key
    source: artifacts/*
    target: artifacts/
    endpoint: https://s3.nl-ams.scw.cloud

---
kind: pipeline
name: rust-nightly

volumes:
- name: cargo-cache
  host:
    path: /var/lib/cargo-cache

steps:
- name: build
  image: rustlang/rust:nightly
  failure: ignore
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build

- name: test
  image: rustlang/rust:nightly
  failure: ignore
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test

---
kind: signature
hmac: 92b051a194f055d0f480821f900776c2ffc4b287e69c13a9bb4fd3101531449a

...
