---
kind: pipeline
name: rust-stable

volumes:
- name: cargo-cache
  host:
    path: /var/lib/cargo-cache

steps:
- name: build
  image: rust:1.46
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build

- name: test
  image: rust:1.46
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test
    - git rev-parse HEAD > .tags

- name: release
  image: rust:1.46
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build --release

- name: prep-upload
  image: rust:1.46
  commands:
    - mkdir -p artifacts/builds/$DRONE_BUILD_NUMBER
    - git archive $DRONE_COMMIT | bzip2 > artifacts/builds/$DRONE_BUILD_NUMBER/$DRONE_REPO_NAME-$DRONE_COMMIT.tar.bz2
    - cp target/release/meta-matrix artifacts/builds/$DRONE_BUILD_NUMBER/meta-matrix-linux-amd64

- name: upload-artifacts
  image: plugins/s3
  settings:
    bucket: meta-matrix
    access_key:
      from_secret: s3_access_key
    secret_key:
      from_secret: s3_secret_key
    source: artifacts/**/*
    target: /
    acl: public-read
    region: nl-ams
    endpoint: https://s3.nl-ams.scw.cloud

---
kind: pipeline
name: rust-nightly

volumes:
- name: cargo-cache
  host:
    path: /var/lib/cargo-cache

steps:
- name: build
  image: rustlang/rust:nightly
  failure: ignore
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo build

- name: test
  image: rustlang/rust:nightly
  failure: ignore
  volumes:
    - name: cargo-cache
      path: /tmp/cargo-cache
  environment:
    CARGO_HOME: /tmp/cargo-cache
  commands:
    - cargo test

---
kind: signature
hmac: 4e0f58a65872e891c5f0b7c025013f6d84824839cd86ffceadb5c64ad78dedb5

...
